export const placeholderProducts = [
  {
    id: "1",
    name: "Casco Integral Pro-X",
    category: "Cascos",
    price: 350000,
    stock: 15,
    image: "https://picsum.photos/400/400?random=1",
    hint: "motorcycle helmet",
  },
  {
    id: "2",
    name: "Llantas Michelin Pilot",
    category: "Llantas",
    price: 450000,
    stock: 8,
    image: "https://picsum.photos/400/400?random=2",
    hint: "motorcycle tire",
  },
  {
    id: "3",
    name: "Aceite Motul 7100 4T",
    category: "Aceites y lubricantes",
    price: 85000,
    stock: 30,
    image: "https://picsum.photos/400/400?random=3",
    hint: "motor oil",
  },
  {
    id: "4",
    name: "Pastillas de Freno Brembo",
    category: "Frenos",
    price: 120000,
    stock: 25,
    image: "https://picsum.photos/400/400?random=4",
    hint: "brake pads",
  },
  {
    id: "5",
    name: "Batería Yuasa YTZ10S",
    category: "Baterías",
    price: 280000,
    stock: 12,
    image: "https://picsum.photos/400/400?random=5",
    hint: "motorcycle battery",
  },
  {
    id: "6",
    name: "Exploradoras LED",
    category: "Accesorios/Iluminación",
    price: 180000,
    stock: 40,
    image: "https://picsum.photos/400/400?random=6",
    hint: "motorcycle lights",
  },
    {
    id: "7",
    name: "Chaqueta de Protección",
    category: "Accesorios",
    price: 650000,
    stock: 10,
    image: "https://picsum.photos/400/400?random=7",
    hint: "motorcycle jacket",
  },
  {
    id: "8",
    name: "Guantes de Cuero",
    category: "Accesorios",
    price: 150000,
    stock: 50,
    image: "https://picsum.photos/400/400?random=8",
    hint: "motorcycle gloves",
  },
];
